"""
Export the star catalog alone for the ring page (docs/stars.js).

The ring page needs the stars but not the 500,000-satellite constellation,
which is most of docs/data.js (about 2.9 MB). This writes the same star
records export_web_data.py packs, ra, dec, mag and colour index as
little-endian float32 from hyg_naked_eye.npz with the Sun dropped, so
physics.loadStars reads them unchanged. About 190 kB.

    python3 export_ring_stars.py      # writes docs/stars.js
"""

import base64
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "docs", "stars.js")


def main():
    d = np.load(os.path.join(HERE, "hyg_naked_eye.npz"))
    keep = d["mag"] > -20  # drop the Sun
    stars = np.stack(
        [d["ra"][keep], d["dec"][keep], d["mag"][keep], d["ci"][keep]], axis=1
    ).astype("<f4")
    manifest = {"stars": {"n": int(keep.sum()), "offset": 0}}
    with open(OUT, "w") as f:
        f.write("// Generated by export_ring_stars.py. Do not edit.\n")
        f.write("// The HYG naked-eye catalog (CC BY-SA), as packed in data.js.\n")
        f.write("window.ODC_STARS_MANIFEST = %s;\n" % json.dumps(manifest))
        f.write(
            'window.ODC_STARS_BLOB = "%s";\n'
            % base64.b64encode(stars.tobytes()).decode()
        )
    print(
        "stars: %d, wrote %s, %.0f kB" % (keep.sum(), OUT, os.path.getsize(OUT) / 1e3)
    )


if __name__ == "__main__":
    main()
