"""
Export the constellation and star catalog for the browser version (docs/).

The browser app does not regenerate the constellation. It loads the exact
layout that lsm.build_sso produces here, for the same seed, so every count it
shows is the count this repository reports. Regenerating it in JavaScript with
a different random number generator would give a statistically equivalent sky
and different numbers: at an equinox the mitigated count moves by about 30%
between plane realisations (raan_sensitivity.py), which is too much to leave
to chance in something people will compare against the README.

Encoding. Within a plane the satellites sit at

    th0[p, k] = 2 pi k / per + offset[p] + jitter[p, k]

so each plane stores one float64 offset and each satellite one int16 jitter
with a least significant bit of 1e-7 rad. Reconstruction error is under
5e-8 rad, about 0.4 m along track. Two bytes per satellite.

Two variants are exported: the +/- 10 degree node spread used everywhere in
this repository, and the +/- 30 degree tolerance SpaceX filed.

    python3 export_web_data.py        # writes docs/data.js
"""

import base64
import json
import os

import numpy as np

import lsm as L

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "docs", "data.js")
SEED = 5
SPREADS = (10.0, 30.0)
LSB = 1e-7                                    # rad per jitter count


def pack_constellation(relax):
    cons = L.build_sso(500_000, relax_deg=relax, seed=SEED)
    groups, blobs = [], []
    worst = 0.0
    for c in cons:
        n_planes, per = c["th0"].shape
        lin = 2 * np.pi * np.arange(per) / per
        resid = c["th0"] - lin[None, :]
        off = np.median(resid, axis=1)
        jit = resid - off[:, None]
        q = np.round(jit / LSB)
        if np.abs(q).max() > 32767:
            raise SystemExit("jitter overflow in int16; raise LSB")
        rec = lin[None, :] + off[:, None] + q * LSB
        worst = max(worst, float(np.abs(rec - c["th0"]).max()))
        planes = np.concatenate([c["node"], c["m"], c["a"][:, None],
                                 c["n"][:, None], off[:, None]], axis=1)
        groups.append(dict(n_planes=int(n_planes), per=int(per)))
        blobs.append((planes.astype("<f8").tobytes(), q.astype("<i2").tobytes()))
    return groups, blobs, worst


def main():
    manifest = {"seed": SEED, "lsb": LSB, "variants": {}}
    chunks = []

    def add(b):
        off = sum(len(x) for x in chunks)
        # keep every array 8-byte aligned so typed-array views are legal
        pad = (-off) % 8
        if pad:
            chunks.append(b"\0" * pad)
            off += pad
        chunks.append(b)
        return off

    for relax in SPREADS:
        groups, blobs, worst = pack_constellation(relax)
        for g, (pl, jq) in zip(groups, blobs):
            g["planes_offset"] = add(pl)
            g["jitter_offset"] = add(jq)
        manifest["variants"][str(int(relax))] = {"groups": groups}
        print("spread +/-%2d: %s satellites, max reconstruction error %.1e rad"
              % (relax, format(sum(g["n_planes"] * g["per"] for g in groups), ","),
                 worst))

    here = os.path.dirname(os.path.abspath(__file__))
    d = np.load(os.path.join(here, "hyg_naked_eye.npz"))
    keep = d["mag"] > -20                                  # drop the Sun
    stars = np.stack([d["ra"][keep], d["dec"][keep], d["mag"][keep],
                      d["ci"][keep]], axis=1).astype("<f4")
    manifest["stars"] = {"n": int(keep.sum()), "offset": add(stars.tobytes())}
    print("stars: %d" % keep.sum())

    blob = b"".join(chunks)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Generated by export_web_data.py. Do not edit.\n")
        f.write("// Exact constellation layout from lsm.build_sso(seed=%d) and "
                "the HYG naked-eye catalog (CC BY-SA).\n" % SEED)
        f.write("window.ODC_MANIFEST = %s;\n" % json.dumps(manifest))
        f.write("window.ODC_BLOB = \"%s\";\n" % base64.b64encode(blob).decode())
    print("wrote %s, %.2f MB" % (OUT, os.path.getsize(OUT) / 1e6))


if __name__ == "__main__":
    main()
